################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/climate_screen/ClimatePresenter.cpp \
C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/climate_screen/ClimateView.cpp \
C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/default_screen/DefaultPresenter.cpp \
C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/default_screen/DefaultView.cpp \
C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/common/FrontendApplication.cpp \
C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/lights_screen/LightsPresenter.cpp \
C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/lights_screen/LightsView.cpp \
C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/main_screen/MainPresenter.cpp \
C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/main_screen/MainView.cpp \
C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/model/Model.cpp \
C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/music_screen/MusicPresenter.cpp \
C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/music_screen/MusicView.cpp \
C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/security_screen/SecurityPresenter.cpp \
C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/security_screen/SecurityView.cpp \
C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/splash_screen/SplashPresenter.cpp \
C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/splash_screen/SplashView.cpp 

OBJS += \
./Application/User/gui/ClimatePresenter.o \
./Application/User/gui/ClimateView.o \
./Application/User/gui/DefaultPresenter.o \
./Application/User/gui/DefaultView.o \
./Application/User/gui/FrontendApplication.o \
./Application/User/gui/LightsPresenter.o \
./Application/User/gui/LightsView.o \
./Application/User/gui/MainPresenter.o \
./Application/User/gui/MainView.o \
./Application/User/gui/Model.o \
./Application/User/gui/MusicPresenter.o \
./Application/User/gui/MusicView.o \
./Application/User/gui/SecurityPresenter.o \
./Application/User/gui/SecurityView.o \
./Application/User/gui/SplashPresenter.o \
./Application/User/gui/SplashView.o 

CPP_DEPS += \
./Application/User/gui/ClimatePresenter.d \
./Application/User/gui/ClimateView.d \
./Application/User/gui/DefaultPresenter.d \
./Application/User/gui/DefaultView.d \
./Application/User/gui/FrontendApplication.d \
./Application/User/gui/LightsPresenter.d \
./Application/User/gui/LightsView.d \
./Application/User/gui/MainPresenter.d \
./Application/User/gui/MainView.d \
./Application/User/gui/Model.d \
./Application/User/gui/MusicPresenter.d \
./Application/User/gui/MusicView.d \
./Application/User/gui/SecurityPresenter.d \
./Application/User/gui/SecurityView.d \
./Application/User/gui/SplashPresenter.d \
./Application/User/gui/SplashView.d 


# Each subdirectory must supply rules for building sources it contributes
Application/User/gui/ClimatePresenter.o: C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/climate_screen/ClimatePresenter.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m33 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Utilities/JPEG -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye" -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye/Components" -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/ClimateView.o: C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/climate_screen/ClimateView.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m33 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Utilities/JPEG -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye" -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye/Components" -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/DefaultPresenter.o: C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/default_screen/DefaultPresenter.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m33 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Utilities/JPEG -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye" -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye/Components" -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/DefaultView.o: C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/default_screen/DefaultView.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m33 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Utilities/JPEG -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye" -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye/Components" -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/FrontendApplication.o: C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/common/FrontendApplication.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m33 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Utilities/JPEG -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye" -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye/Components" -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/LightsPresenter.o: C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/lights_screen/LightsPresenter.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m33 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Utilities/JPEG -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye" -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye/Components" -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/LightsView.o: C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/lights_screen/LightsView.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m33 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Utilities/JPEG -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye" -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye/Components" -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/MainPresenter.o: C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/main_screen/MainPresenter.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m33 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Utilities/JPEG -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye" -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye/Components" -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/MainView.o: C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/main_screen/MainView.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m33 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Utilities/JPEG -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye" -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye/Components" -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/Model.o: C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/model/Model.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m33 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Utilities/JPEG -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye" -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye/Components" -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/MusicPresenter.o: C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/music_screen/MusicPresenter.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m33 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Utilities/JPEG -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye" -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye/Components" -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/MusicView.o: C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/music_screen/MusicView.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m33 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Utilities/JPEG -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye" -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye/Components" -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/SecurityPresenter.o: C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/security_screen/SecurityPresenter.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m33 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Utilities/JPEG -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye" -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye/Components" -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/SecurityView.o: C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/security_screen/SecurityView.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m33 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Utilities/JPEG -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye" -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye/Components" -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/SplashPresenter.o: C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/splash_screen/SplashPresenter.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m33 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Utilities/JPEG -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye" -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye/Components" -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/SplashView.o: C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/TouchGFX/gui/src/splash_screen/SplashView.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m33 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U5G9xx -c -I../../Core/Inc -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../Utilities/JPEG -I../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/FreeRTOS/Source/include/ -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure/ -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/ -I../../Middlewares/Third_Party/CMSIS/RTOS2/Include/ -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/generated/videos/include -I../../TouchGFX/gui/include -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye" -I"C:/Users/HananHunain/Downloads/Bitbucket/DE_4/Repo/DragonEyeU5_4S/STM32CubeIDE/Application/User/TouchGFX/target/DragonEye/Components" -I../../Middlewares/ST/touchgfx_components/gpu2d/NemaGFX/include -I../../Middlewares/ST/touchgfx_components/gpu2d/TouchGFXNema/include -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Application-2f-User-2f-gui

clean-Application-2f-User-2f-gui:
	-$(RM) ./Application/User/gui/ClimatePresenter.cyclo ./Application/User/gui/ClimatePresenter.d ./Application/User/gui/ClimatePresenter.o ./Application/User/gui/ClimatePresenter.su ./Application/User/gui/ClimateView.cyclo ./Application/User/gui/ClimateView.d ./Application/User/gui/ClimateView.o ./Application/User/gui/ClimateView.su ./Application/User/gui/DefaultPresenter.cyclo ./Application/User/gui/DefaultPresenter.d ./Application/User/gui/DefaultPresenter.o ./Application/User/gui/DefaultPresenter.su ./Application/User/gui/DefaultView.cyclo ./Application/User/gui/DefaultView.d ./Application/User/gui/DefaultView.o ./Application/User/gui/DefaultView.su ./Application/User/gui/FrontendApplication.cyclo ./Application/User/gui/FrontendApplication.d ./Application/User/gui/FrontendApplication.o ./Application/User/gui/FrontendApplication.su ./Application/User/gui/LightsPresenter.cyclo ./Application/User/gui/LightsPresenter.d ./Application/User/gui/LightsPresenter.o ./Application/User/gui/LightsPresenter.su ./Application/User/gui/LightsView.cyclo ./Application/User/gui/LightsView.d ./Application/User/gui/LightsView.o ./Application/User/gui/LightsView.su ./Application/User/gui/MainPresenter.cyclo ./Application/User/gui/MainPresenter.d ./Application/User/gui/MainPresenter.o ./Application/User/gui/MainPresenter.su ./Application/User/gui/MainView.cyclo ./Application/User/gui/MainView.d ./Application/User/gui/MainView.o ./Application/User/gui/MainView.su ./Application/User/gui/Model.cyclo ./Application/User/gui/Model.d ./Application/User/gui/Model.o ./Application/User/gui/Model.su ./Application/User/gui/MusicPresenter.cyclo ./Application/User/gui/MusicPresenter.d ./Application/User/gui/MusicPresenter.o ./Application/User/gui/MusicPresenter.su ./Application/User/gui/MusicView.cyclo ./Application/User/gui/MusicView.d ./Application/User/gui/MusicView.o ./Application/User/gui/MusicView.su ./Application/User/gui/SecurityPresenter.cyclo ./Application/User/gui/SecurityPresenter.d ./Application/User/gui/SecurityPresenter.o ./Application/User/gui/SecurityPresenter.su ./Application/User/gui/SecurityView.cyclo ./Application/User/gui/SecurityView.d ./Application/User/gui/SecurityView.o ./Application/User/gui/SecurityView.su ./Application/User/gui/SplashPresenter.cyclo ./Application/User/gui/SplashPresenter.d ./Application/User/gui/SplashPresenter.o ./Application/User/gui/SplashPresenter.su ./Application/User/gui/SplashView.cyclo ./Application/User/gui/SplashView.d ./Application/User/gui/SplashView.o ./Application/User/gui/SplashView.su

.PHONY: clean-Application-2f-User-2f-gui

